name: pulumi-up
description: Run pulumi up

inputs:
  backend:
    description: pulumi backend url to log in to
    required: false
  diff:
    description: show detailed changes diff
    required: false
    default: "true"
  github-token:
    description: github token used to post comments and fetch plugins
    required: false
    default: ${{ github.token }}
  runtime:
    description: pulumi runtime (eg. python, nodejs, go, etc.)
    required: false
    default: python
  runtime-cache:
    description: pulumi runtime package maangere for cache setup (eg. pip, npm, etc.)
    required: false
    default: pip
  runtime-deps-file:
    description: pulumi dependencies file name (eg. requirements.txt for python runtime)
    required: false
    default: requirements.txt
  runtime-version:
    description: pulumi runtime version (eg. '3.12.0' for Python)
    required: false
    # renovate: datasource=github-releases depName=python packageName=actions/python-versions
    default: 3.12.1
  stack:
    description: pulumi stack to use
    required: true
  token:
    description: pulumi access token
    required: true
  version:
    description: pulumi version to install
    required: false
    # renovate: datasource=pypi depName=pulumi
    default: 3.103.1
  workdir:
    description: change working directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup Python
      if: inputs.runtime == 'python'
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ inputs.runtime-version }}
        cache: ${{ inputs.runtime-cache }}

    - name: Setup Node
      if: inputs.runtime == 'nodejs'
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        node-version: ${{ inputs.runtime-version }}
        cache: ${{ inputs.runtime-cache }}

    - name: Setup Go
      if: inputs.runtime == 'go'
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version: ${{ inputs.runtime-version }}

    - name: Setup Pulumi cache
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: |
          ~/.pulumi/
          !~/.pulumi/credentials.json
        key: pulumi-${{ hashFiles(format('{0}/{1}', inputs.workdir, inputs.runtime-deps-file)) }}
        restore-keys: pulumi-

    - name: Apply changes
      uses: pulumi/actions@76683de37aa44910871ba6cef36557780f2e41d1 # v5.1.1
      with:
        cloud-url: ${{ inputs.backend }}
        command: up
        comment-on-pr: true
        comment-on-summary: true
        diff: ${{ inputs.diff }}
        github-token: ${{ inputs.github-token }}
        pulumi-version: ${{ inputs.version }}
        stack-name: ${{ inputs.stack }}
        work-dir: ${{ inputs.workdir }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PULUMI_ACCESS_TOKEN: ${{ inputs.token }}
