name: pre-commit
description: Run pre-commit hooks

inputs:
  args:
    description: arguments to pass to pre-commit run
    required: false
    default: --all-files
  python-version:
    description: python version
    required: false
    # renovate: datasource=github-releases depName=python packageName=actions/python-versions
    default: 3.12.3
  skip:
    description: comma separated list of hooks id to skip
    required: false
    default: no-commit-to-branch
  version:
    description: pre-commit version
    required: false
    # renovate: datasource=pypi depName=pre-commit
    default: 3.7.1
  workdir:
    description: change working directory for pre-commit run
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pre-commit virtualenv
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        key: pre-commit-venv-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}
        path: .venv

    - name: Install pre-commit
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install pre-commit==${{ inputs.version }}
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

    - name: Restore pre-commit cache
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}-
          pre-commit-py${{ steps.setup-python.outputs.python-version }}-
          pre-commit-
      id: cache-pre-commit

    - name: Install pre-commit hooks
      shell: bash
      run: pre-commit install-hooks

    - name: Save pre-commit cache
      if: steps.cache-pre-commit.outputs.cache-hit != 'true'
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.args }}
      env:
        SKIP: ${{ inputs.skip }}
