name: pulumi-up-py
description: Run pulumi up with Python SDK

inputs:
  backend:
    description: pulumi backend url to log in to
    required: false
  poetry-version:
    description: poetry version
    required: false
    # renovate: datasource=pypi depName=poetry
    default: 1.6.1
  python-version:
    description: python version
    required: false
    # renovate: datasource=github-releases depName=actions/python-versions
    default: 3.11.5
  stack:
    description: pulumi stack to use
    required: true
  token:
    description: pulumi access token
    required: true
  version:
    description: pulumi version to install
    required: false
    # renovate: datasource=pypi depName=pulumi
    default: 3.85.0
  workdir:
    description: change working directory
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Install Poetry
      shell: bash
      run: pipx install poetry==${{ inputs.poetry-version }}

    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - name: Install project dependencies
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: poetry install

    - name: Append virtualenv to PATH
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: echo "$(poetry env info --path)/bin" >> "$GITHUB_PATH"

    - name: Apply changes
      uses: pulumi/actions@1d3ebd326317f249313706eeb489c9ed7c036443 # v4.5.0
      with:
        pulumi-version: ${{ inputs.version }}
        work-dir: ${{ inputs.workdir }}
        command: up
        cloud-url: ${{ inputs.backend }}
        stack-name: ${{ inputs.stack }}
        comment-on-pr: true
        comment-on-summary: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.token }}
