name: getsops
description: Install SOPS

inputs:
  version:
    description: sops version
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Install SOPS
      uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4 # v1.12.0
      with:
        repo: getsops/sops
        tag: ${{ inputs.version }}
        cache: enable
        extension-matching: disable
        rename-to: sops
        chmod: 0755
