name: getsops
description: Install SOPS

inputs:
  version:
    description: "sops version (ex: v3.9.0)"
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Set version
      shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        INPUT_VERSION: ${{ inputs.version }}
