name: pre-commit-monorepo
description: Run pre-commit hooks in a monorepo context

inputs:
  args:
    description: arguments to pass to pre-commit run
    required: false
  python-version:
    description: python version
    required: false
    # renovate: datasource=github-releases depName=python packageName=actions/python-versions
    default: 3.12.1
  skip:
    description: comma separated list of hooks id to skip
    required: false
    default: no-commit-to-branch
  version:
    description: pre-commit version
    required: false
    # renovate: datasource=pypi depName=pre-commit
    default: 3.5.0
  workdir:
    description: change working directory for pre-commit run
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pre-commit virtualenv
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        key: pre-commit-venv-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}
        path: .venv

    - name: Install pre-commit
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install pre-commit==${{ inputs.version }}
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

    - name: Restore pre-commit cache
      uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}-
          pre-commit-py${{ steps.setup-python.outputs.python-version }}-
          pre-commit-
      id: cache-pre-commit

    - name: Install pre-commit hooks
      shell: bash
      run: pre-commit install-hooks

    - name: Save pre-commit cache
      if: steps.cache-pre-commit.outputs.cache-hit != 'true'
      uses: actions/cache/save@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-py${{ steps.setup-python.outputs.python-version }}-pc${{ inputs.version }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run pre-commit in working directory
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: git ls-files -- . | xargs pre-commit run --show-diff-on-failure --color=always ${{ inputs.args }} --files
      env:
        SKIP: ${{ inputs.skip }}
