name: pre-commit-monorepo
description: Run pre-commit hooks in a monorepo context

inputs:
  args:
    description: arguments to pass to pre-commit run
    required: false
  python-version:
    description: python version
    required: false
    # renovate: datasource=github-releases depName=actions/python-versions
    default: 3.11.5
  skip:
    description: comma separated list of hooks id to skip
    required: false
    default: no-commit-to-branch
  version:
    description: pre-commit version
    required: false
    # renovate: datasource=pypi depName=pre-commit
    default: 3.4.0
  workdir:
    description: change working directory for pre-commit run
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup pre-commit cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ inputs.python }}-${{ hashFiles('.pre-commit-config.yaml') }}
          pre-commit-${{ inputs.python }}-
          pre-commit-

    - name: Install pre-commit
      shell: bash
      run: pipx install pre-commit==${{ inputs.version }}
      env:
        PIPX_DEFAULT_PYTHON: ${{ steps.setup-python.outputs.python-path }}

    - name: Instal pre-commit hooks
      shell: bash
      run: pre-commit install-hooks

    - name: Run pre-commit in working directory
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: git ls-files -- . | xargs pre-commit run --show-diff-on-failure --color=always ${{ inputs.args }} --files
      env:
        SKIP: ${{ inputs.skip }}
