name: setup-rye
description: Install Rye, the package manager for Python

inputs:
  install_option:
    description: Options to be passed to the installer
    required: false
    default: --yes
  version:
    description: Rye version to install
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Cache Rye installation
      uses: actions/cache@main
      with:
        path: ~/.rye
        key: ${{ runner.os }}-rye-${{ inputs.version }}
        restore-keys: |
          ${{ runner.os }}-rye-${{ inputs.version }}
          ${{ runner.os }}-rye-

    - name: Install Rye
      shell: bash
      run: curl -sSf https://rye.astral.sh/get | bash
      env:
        RYE_INSTALL_OPTION: ${{ inputs.install_option }}
        RYE_VERSION: ${{ inputs.version }}

    - name: Append Rye to PATH
      shell: bash
      run: echo "$HOME/.rye/shims" >> "$GITHUB_PATH"
