name: setup-rye
description: Install Rye, the package manager for Python

inputs:
  install_option:
    description: Options to be passed to the installer
    required: false
    default: --yes
  version:
    description: Rye version to install
    required: false
    # renovate: datasource=github-releases depName=rye packageName=mitsuhiko/rye
    default: 0.33.0

runs:
  using: composite
  steps:
    - name: Cache Rye installation
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.rye
        key: ${{ runner.os }}-rye-${{ inputs.version }}

    - name: Install Rye
      shell: bash
      run: curl -sSf https://rye-up.com/get | bash
      env:
        RYE_INSTALL_OPTION: ${{ inputs.install_option }}
        RYE_VERSION: ${{ inputs.version }}

    - name: Append Rye to PATH
      shell: bash
      run: echo "$HOME/.rye/shims" >> "$GITHUB_PATH"
