name: CI / Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  action:
    name: Action
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Run
        uses: nikaro/actions/getsops@fix/getsops
